### Site info:
title: 学习笔记 
tagline: slow is fast. 
author: zhenghua
email: sparkling.zou@gmail.com 
description: "Read Think Create." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "zhenghua, 邹政华, meiyueyibenshu, zou zhenghua"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhenghua.info"   # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username:   
github_username:  yihaozou 
disqus_shortname: yihaozou 
favicon:     "/images/favicon.ico"
aboutme: "Hi,我是邹政华，欢迎访问我的博客。
邮箱：sparkling.zou@gmail.com    "# these are shown on aboutme-sidebar.
aboutme_photo: "/images/favicon.ico" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Resent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 3

# Gems
plugins: [jekyll-paginate]
